name: BusinessManagement
favicon: null
layout_spectrum: 0.4782486988697201
typography_spectrum: 0.0047223204746842384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.28991920896805823
  lightness: 0.6545118512585759
  saturation: 0.9511664395686239
  rhythmicContrast: 0.6673291746992618
purpose: []
